<a href="https://colab.research.google.com/github/Davron030901/PyTorch/blob/main/Mastering_Activation_Functions_in_PyTorch_A_Deep_Dive_Tutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
import torch.nn as nn
import torch.optim as optim

In [ ]:
logits=torch.tensor([[1.4,2.3,0.4],[3.1,4.5,1.2],[5.3,6.1,2.3]])
softmax_prob=torch.softmax(logits,dim=1)
print(softmax_prob)

tensor([[0.2613, 0.6426, 0.0961],
        [0.1921, 0.7791, 0.0287],
        [0.3053, 0.6795, 0.0152]])


In [ ]:
class SimpleNN(nn.Module):
  def __init__(self,input_size,hidden_size,output_size):
    super(SimpleNN,self).__init__()
    self.layer1=nn.Linear(input_size,hidden_size)
    self.LeakyReLU=nn.LeakyReLU(negative_slope=0.01)
    self.layer2=nn.Linear(hidden_size,output_size)

  def forward(self,x):
    x=self.layer1(x)
    x=self.LeakyReLU(x)
    x=self.layer2(x)
    return x

input_size=10
hidden_size=20
output_size=1
model=SimpleNN(input_size,hidden_size,output_size)
input_data=torch.randn(5,input_size)
output=model(input_data)
print(input_data)
print(output)

tensor([[-0.9309, -1.5090,  0.3395, -2.1397, -0.0748, -0.3832,  0.3487, -0.2779,
         -0.6705, -0.0943],
        [-1.8981,  0.9707,  1.0471,  1.7087,  0.1762,  0.8785, -0.0170, -0.6419,
          0.6187, -0.2305],
        [ 0.1195, -0.1614, -0.4748, -1.4827, -1.1109,  0.4563,  0.0700, -1.4877,
          0.3422,  0.0237],
        [-1.0173,  1.0003, -0.8064,  1.1714,  0.2777, -0.6595,  0.6758,  0.6004,
          0.1873, -0.3918],
        [-1.4082, -0.4773,  0.3499, -0.1414,  0.5037,  0.9247, -0.2078,  0.2465,
         -2.0747, -0.8265]])
tensor([[ 0.2263],
        [ 0.1494],
        [-0.2349],
        [ 0.0996],
        [ 0.3525]], grad_fn=<AddmmBackward0>)


In [ ]:
class SimpleNN(nn.Module):
  def __init__(self,input_size,hidden_size,output_size):
    super(SimpleNN,self).__init__()
    self.layer1=nn.Linear(input_size,hidden_size)
    self.layer2=nn.Linear(hidden_size,output_size)

  def forward(self,x):
    x_relu=torch.relu(self.layer1(x))
    x_selu=torch.selu(self.layer2(x_relu))

    return x_relu,x_selu

input_size=10
hidden_size=20
output_size=1
model=SimpleNN(input_size,hidden_size,output_size)
input_data=torch.randn(5,input_size)
output_relu,output_selu=model(input_data)
print(input_data)
print(output_relu)
print(output_selu)

tensor([[ 2.2015,  1.1001, -1.7296,  1.1043, -0.5864,  0.5490,  1.1821, -0.0834,
         -1.9049, -1.0122],
        [ 0.1710, -0.3361, -1.5771,  0.3200,  1.2071,  1.3148, -0.4396, -1.5212,
         -0.1581, -1.0945],
        [ 0.3468, -0.1763,  0.7764,  0.8102, -1.3870,  0.6749, -0.0646,  2.6456,
          0.0823, -0.3917],
        [-0.9428, -0.6505, -0.6034, -0.5406, -1.2468, -0.0877,  1.6348,  0.1252,
          2.1810, -1.1011],
        [ 0.3045,  0.1632,  0.6617,  1.4008, -0.3877, -1.9341, -1.0179,  0.1888,
          0.8629,  1.0269]])
tensor([[0.0000, 0.0000, 0.9077, 1.1480, 0.0000, 0.7637, 0.9252, 1.0827, 0.0000,
         0.0000, 0.0000, 0.3682, 1.5818, 0.0000, 0.0000, 0.0398, 1.5983, 0.0807,
         0.0000, 0.4339],
        [0.0000, 0.0000, 0.0000, 0.0000, 0.0421, 0.1485, 0.7263, 0.0000, 0.0000,
         0.4588, 0.0000, 0.0958, 0.5479, 0.0000, 0.0000, 0.0575, 0.7311, 0.0000,
         0.0000, 0.0198],
        [0.0000, 0.0924, 0.9607, 0.7203, 0.0000, 0.0000, 0.0000, 1.4013, 0.249