<a href="https://colab.research.google.com/github/Davron030901/PyTorch/blob/main/PyTorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [51]:
import torch
import numpy as np

In [52]:
tensor_1 = torch.tensor([1,2,3])
print("Our first PyTorch Tensor:",tensor_1)

Our first PyTorch Tensor: tensor([1, 2, 3])


In [53]:
array_1 = np.array([1,2,3])
print("Our first NumPy Array:",array_1)

Our first NumPy Array: [1 2 3]


In [54]:
tensor_from_numpy=torch.tensor(array_1)
print("Our first PyTorch Tensor from NumPy Array:",tensor_from_numpy)

Our first PyTorch Tensor from NumPy Array: tensor([1, 2, 3])


In [55]:
empty_tensot=torch.empty(3)
print("Our first Empty Tensor:",empty_tensot)

Our first Empty Tensor: tensor([4.1881e-11, 1.0606e-08, 2.9573e-18])


In [56]:
zero_tensor=torch.zeros(2,3)
print("Our first Zero Tensor:",zero_tensor)

Our first Zero Tensor: tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [57]:
one_tensor=torch.ones(2,3)
print("Our first one Tensor:",one_tensor)

Our first one Tensor: tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [58]:
random_tensor=torch.rand(3,3)
print("Our first Random Tensor:",random_tensor)

Our first Random Tensor: tensor([[0.4658, 0.7857, 0.4665],
        [0.8195, 0.8616, 0.8466],
        [0.1829, 0.0200, 0.2541]])


In [59]:
arrange_tensor=torch.arange(0,100,10)
print("Our first Arrange Tensor:",arrange_tensor)

Our first Arrange Tensor: tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])


In [60]:
random_tensor[1,1]

tensor(0.8616)

In [61]:
random_tensor[1,:]

tensor([0.8195, 0.8616, 0.8466])

In [62]:
random_tensor[:,0]

tensor([0.4658, 0.8195, 0.1829])

In [63]:
random_tensor[1,1].item()

0.8616231083869934

In [64]:
reshape_tensor=torch.rand(5,4)
print("Our first Reshape Tensor:",reshape_tensor)

Our first Reshape Tensor: tensor([[0.1599, 0.5025, 0.2130, 0.9356],
        [0.3008, 0.5546, 0.8491, 0.8059],
        [0.2229, 0.9475, 0.8261, 0.9913],
        [0.9736, 0.1592, 0.9469, 0.9898],
        [0.0705, 0.9239, 0.4946, 0.2232]])


In [65]:
new_reshape_tensor=reshape_tensor.view(-1,2)
print("Our first New Reshape Tensor:",new_reshape_tensor)

Our first New Reshape Tensor: tensor([[0.1599, 0.5025],
        [0.2130, 0.9356],
        [0.3008, 0.5546],
        [0.8491, 0.8059],
        [0.2229, 0.9475],
        [0.8261, 0.9913],
        [0.9736, 0.1592],
        [0.9469, 0.9898],
        [0.0705, 0.9239],
        [0.4946, 0.2232]])


In [66]:
tensor_a=torch.tensor([1,2,3])
tensor_b=torch.tensor([4,5,6])

result_add_1=torch.add(tensor_b,tensor_a)
print("Our first Add Tensor:",result_add_1)

Our first Add Tensor: tensor([5, 7, 9])


In [67]:
result_add_2=tensor_a+tensor_b
print("Our second Add Tensor:",result_add_2)

Our second Add Tensor: tensor([5, 7, 9])


In [68]:
result_sub_1=torch.sub(tensor_b,tensor_a)
print("Our first Sub Tensor:",result_sub_1)

Our first Sub Tensor: tensor([3, 3, 3])


In [69]:
tensor_b.add_(tensor_a)
print("Our sird Add Tensor:",tensor_b)

Our sird Add Tensor: tensor([5, 7, 9])


[2,4]x[4,3]

In [70]:
matrix_a=torch.tensor([[2,4],[6,8]])
matrix_b=torch.tensor([[3,5],[7,9]])

In [71]:
print("Our first Matrix:",matrix_a)
print("Our second Matrix:",matrix_b)

Our first Matrix: tensor([[2, 4],
        [6, 8]])
Our second Matrix: tensor([[3, 5],
        [7, 9]])


In [72]:
result_multiply=torch.mm(matrix_a,matrix_b)
print("Our first Multiply Tensor:",result_multiply)

Our first Multiply Tensor: tensor([[ 34,  46],
        [ 74, 102]])


In [73]:
result_multiply_2=matrix_a@matrix_b
print("Our second Multiply Tensor:",result_multiply_2)

Our second Multiply Tensor: tensor([[ 34,  46],
        [ 74, 102]])


In [74]:
result_multiply_3=torch.mul(matrix_a,matrix_b)
print("Our third Multiply Tensor:",result_multiply_3)

Our third Multiply Tensor: tensor([[ 6, 20],
        [42, 72]])


In [75]:
result_multiply_4=matrix_a*matrix_b
print("Our fourth Multiply Tensor:",result_multiply_4)

Our fourth Multiply Tensor: tensor([[ 6, 20],
        [42, 72]])


In [76]:
result_multiply_3=torch.matmul(matrix_a,matrix_b)
print("Our third Multiply Tensor:",result_multiply_3)

Our third Multiply Tensor: tensor([[ 34,  46],
        [ 74, 102]])


In [77]:
result_multiply_4=matrix_a.mm(matrix_b)
print("Our fourth Multiply Tensor:",result_multiply_4)

Our fourth Multiply Tensor: tensor([[ 34,  46],
        [ 74, 102]])


In [78]:
result_multiply.dtype

torch.int64

In [79]:
random_tensor.dtype

torch.float32

In [80]:
tensor_int=torch.tensor([4,5,6],dtype=torch.int64)
print("Our first Int Tensor:",tensor_int)
print("Our first Int Tensor:",tensor_int.dtype)

Our first Int Tensor: tensor([4, 5, 6])
Our first Int Tensor: torch.int64


In [81]:
tensor_float=tensor_int.to(torch.float32)

In [82]:
print("Our first Float Tensor:",tensor_float)
print("Our first Float Tensor:",tensor_float.dtype)

Our first Float Tensor: tensor([4., 5., 6.])
Our first Float Tensor: torch.float32


In [83]:
tensor_float.device

device(type='cpu')

In [84]:
device=torch.device('cuda' if torch.cuda.is_available() else 'cpu')

In [85]:
tensor_float.to(device)

tensor([4., 5., 6.])

In [86]:
tensor_float.device

device(type='cpu')

In [87]:
torch.cuda.device_count()

0

In [88]:
tensor_new=torch.tensor([51.4,46.2,39.3],dtype=torch.float32,device=device)

In [89]:
tensor_new.shape

torch.Size([3])

In [90]:
random_tensor.shape

torch.Size([3, 3])